[".config/nvim"]
    type = "archive"
    url = "https://github.com/flou/nvim/archive/main.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
